//
//  PlanTask.swift
//  DevAscent
//
//  Created by Rishiraj on 24/11/25.
//

import Foundation
import SwiftData

/// Category options for organizing tasks
enum TaskCategory: String, Codable, CaseIterable {
    case core = "Core"
    case learning = "Learning"
    case health = "Health"
    
    var displayName: String { rawValue }
}

/// SwiftData model for daily tasks in the Planner
/// @Model macro automatically generates database schema and enables SwiftData persistence
@Model
final class PlanTask {
    var id: UUID
    var title: String
    var isCompleted: Bool
    var createdAt: Date
    var category: String // Storing as String for SwiftData compatibility
    var isAISuggested: Bool
    
    /// Initialize a new task
    /// - Parameters:
    ///   - title: The task description
    ///   - category: Task category (Core, Learning, Health)
    ///   - isAISuggested: Whether this task was generated by AI
    init(
        title: String,
        category: TaskCategory = .core,
        isAISuggested: Bool = false
    ) {
        self.id = UUID()
        self.title = title
        self.isCompleted = false
        self.createdAt = Date()
        self.category = category.rawValue
        self.isAISuggested = isAISuggested
    }
    
    /// Helper computed property to get the category as an enum
    var categoryEnum: TaskCategory {
        TaskCategory(rawValue: category) ?? .core
    }
}
